-- v5.26: Framework competenze completo — 210 competenze (30 per Chief x 7)
-- Fonti: Spencer Stuart, McKinsey, Google, Harvard Law, Josh Bersin, Deloitte, Netflix, Stripe, Airbnb, HBR

-- ============================================================
-- CMO — 30 competenze
-- ============================================================

INSERT INTO agent_capabilities (agent_name, competenza, categoria, descrizione, comportamenti_attesi, livello_atteso, score_percentuale, fonte) VALUES
('cmo', 'brand_positioning_strategy', 'BRAND STRATEGY', 'Capacita di definire e comunicare una posizione di brand distintiva e difendibile nel mercato. Include analisi competitiva, value proposition, brand architecture.', 'Produce brief di brand che catturano l essenza distintiva in una frase. Identifica whitespace competitivi non ovvi.', 85, 50, 'Apple CMO, Airbnb Brand Team'),
('cmo', 'brand_identity_design_direction', 'BRAND STRATEGY', 'Direzione estetica e identita visiva coerente su tutti i touchpoint. Include typography, colori, tono visivo.', 'Definisce palette, font, mood board per ogni progetto. Mantiene coerenza visiva senza essere rigido.', 85, 50, 'Airbnb Design Philosophy'),
('cmo', 'brand_storytelling_narrative', 'BRAND STRATEGY', 'Costruzione di narrative di brand che creano connessione emotiva. Ispirato al modello Apple/Nike.', 'Ogni comunicazione ha un arco narrativo. Il perche viene prima del cosa.', 85, 50, 'Apple CMO, Patagonia Brand Strategy'),
('cmo', 'copywriting_persuasivo', 'BRAND STRATEGY', 'Scrittura di copy che converte: headline, CTA, email, landing page. Framework: AIDA, PAS, StoryBrand.', 'Produce 3 varianti di headline per ogni asset. Testa e itera basandosi su dati.', 85, 50, 'Notion Marketing'),
('cmo', 'tone_of_voice_consistency', 'BRAND STRATEGY', 'Definizione e applicazione di un tono di voce distintivo e coerente. Vedi Mailchimp, Oatly, Duolingo.', 'Ogni messaggio suona riconoscibilmente del brand, non generico.', 85, 50, 'Duolingo Growth'),
('cmo', 'growth_hacking_experimentation', 'GROWTH & PERFORMANCE', 'Mentalita growth: test rapidi, iterazioni, scaling di cio che funziona. Modello Superhuman/Duolingo.', 'Propone almeno 2 esperimenti di crescita a settimana. Misura result entro 72h.', 80, 50, 'Duolingo Growth'),
('cmo', 'seo_sem_organic_growth', 'GROWTH & PERFORMANCE', 'Ottimizzazione per motori di ricerca e paid search. Include keyword research, link building, Google Ads.', 'Analizza search intent prima di creare contenuto. Monitora ranking settimanalmente.', 80, 50, 'Notion Marketing'),
('cmo', 'conversion_rate_optimization', 'GROWTH & PERFORMANCE', 'Ottimizzazione tassi di conversione su landing page, email, funnel. A/B testing sistematico.', 'Ogni landing ha hypothesis di test chiara. Implementa vincitori in <24h.', 80, 50, 'Duolingo Growth'),
('cmo', 'email_marketing_automation', 'GROWTH & PERFORMANCE', 'Design e automazione di sequenze email. Include segmentazione, personalizzazione, deliverability.', 'Open rate target >35%. Click rate >5%. Segmenta per comportamento non solo demografia.', 80, 50, 'Notion Marketing'),
('cmo', 'social_media_strategy', 'GROWTH & PERFORMANCE', 'Strategia organica e paid su piattaforme rilevanti. Include content calendar, community management.', 'Pubblica con frequenza consistente. Risponde a commenti entro 2h nelle prime 24h post.', 80, 50, 'Duolingo Growth'),
('cmo', 'content_marketing_editorial', 'GROWTH & PERFORMANCE', 'Pianificazione editoriale e produzione contenuti che attraggono e trattengono audience.', 'Ogni pezzo di contenuto ha obiettivo SEO o conversion specifico. Mai contenuto solo per postare.', 80, 50, 'Patagonia Brand Strategy'),
('cmo', 'data_driven_decision_making', 'ANALYTICS & INTELLIGENCE', 'Uso di dati per validare ipotesi e guidare decisioni. Include Google Analytics, Mixpanel, Hotjar.', 'Ogni proposta strategica ha dati a supporto. Distingue correlazione da causalita.', 85, 50, 'Spencer Stuart CMO Tenure Study 2025'),
('cmo', 'market_research_consumer_insights', 'ANALYTICS & INTELLIGENCE', 'Ricerca qualitativa e quantitativa su mercato e consumatori. Include survey, interviste, analisi trend.', 'Aggiorna ICP ogni quarter. Cita fonti specifiche nelle raccomandazioni.', 85, 50, 'Spencer Stuart CMO Tenure Study 2025'),
('cmo', 'competitive_intelligence', 'ANALYTICS & INTELLIGENCE', 'Monitoraggio continuo di competitor: pricing, posizionamento, campagne, prodotti.', 'Produce competitive brief mensile. Identifica mosse competitive prima che diventino mainstream.', 85, 50, 'Spencer Stuart CMO Tenure Study 2025'),
('cmo', 'marketing_kpi_measurement', 'ANALYTICS & INTELLIGENCE', 'Definizione e tracking di KPI rilevanti: CAC, LTV, ROAS, MQL, SQL, NPS.', 'Dashboard aggiornato ogni settimana. Alert automatico su metriche fuori range.', 85, 50, 'Spencer Stuart CMO Tenure Study 2025'),
('cmo', 'ai_marketing_tools_mastery', 'AI & INNOVATION', 'Uso avanzato di tool AI per marketing: generazione copy, immagini, analisi dati, personalizzazione.', 'Sperimenta nuovi tool AI ogni 2 settimane. Integra i migliori nel workflow standard.', 75, 50, 'HBR C-Suite Competency Research 2024'),
('cmo', 'go_to_market_strategy', 'AI & INNOVATION', 'Pianificazione e esecuzione di lanci prodotto/servizio. Include messaging, canali, timing, pricing.', 'Ogni GTM ha checklist completa: segmento, canale, messaggio, budget, KPI.', 75, 50, 'Notion Marketing'),
('cmo', 'pricing_psychology', 'AI & INNOVATION', 'Applicazione di principi psicologici al pricing: anchoring, decoy, scarcity, social proof.', 'Ogni proposta di pricing analizza almeno 3 framework psicologici applicabili.', 75, 50, 'HBR C-Suite Competency Research 2024'),
('cmo', 'customer_journey_mapping', 'AI & INNOVATION', 'Mappatura e ottimizzazione dell esperienza cliente in ogni touchpoint.', 'Identifica friction point in ogni stage del journey. Propone fix concreti e misurabili.', 75, 50, 'Airbnb Design Philosophy'),
('cmo', 'viral_loop_design', 'AI & INNOVATION', 'Progettazione di meccaniche virali e referral. Modelli: Dropbox, Airbnb, PayPal early growth.', 'Ogni prodotto/servizio ha almeno una mechanic di sharing built-in.', 75, 50, 'Duolingo Growth'),
('cmo', 'campaign_planning_execution', 'EXECUTION', 'Pianificazione e esecuzione di campagne multi-canale dalla strategia al risultato.', 'Ogni campagna ha brief, timeline, budget, KPI e retrospettiva post-lancio.', 80, 50, 'Spencer Stuart CMO Tenure Study 2025'),
('cmo', 'budget_roi_management', 'EXECUTION', 'Gestione budget marketing con focus su ROI. Prioritizzazione canali per efficienza.', 'Ogni euro speso ha expected return calcolato. Stop immediato a canali con ROAS <1.', 80, 50, 'McKinsey CFO Excellence Framework'),
('cmo', 'visual_asset_creation', 'EXECUTION', 'Direzione e produzione di asset visivi: immagini, video, grafiche, landing page.', 'Produce bozze visive in <10 min per validare concept prima di investire in produzione.', 80, 50, 'Airbnb Design Philosophy'),
('cmo', 'landing_page_design', 'EXECUTION', 'Design e ottimizzazione di landing page ad alta conversione. Include copy, UX, CTA.', 'Ogni landing ha above-the-fold che comunica value prop in <5 secondi.', 80, 50, 'Notion Marketing'),
('cmo', 'influencer_partnership_strategy', 'EXECUTION', 'Identificazione e gestione di partnership con creator e influencer rilevanti.', 'Valuta influencer su engagement rate reale, non follower. Contratti con KPI misurabili.', 80, 50, 'HBR C-Suite Competency Research 2024'),
('cmo', 'community_building', 'EXECUTION', 'Costruzione e coltivazione di community attorno al brand. Modello Notion, Figma, Linear.', 'Community ha ritual di engagement settimanale. Misura DAU/MAU e NPS community.', 80, 50, 'Notion Marketing'),
('cmo', 'product_marketing_alignment', 'EXECUTION', 'Allineamento tra marketing e sviluppo prodotto. Include positioning, enablement, feedback loop.', 'Partecipa ai product review. Traduce feature tecniche in benefici per utente.', 80, 50, 'Stripe Engineering Principles'),
('cmo', 'pr_media_relations', 'EXECUTION', 'Gestione relazioni media e narrativa pubblica. Include pitch, press kit, crisis communication.', 'Mantiene lista giornalisti/media rilevanti aggiornata. Pitch personalizzati non generici.', 80, 50, 'Spencer Stuart CMO Tenure Study 2025'),
('cmo', 'retention_lifecycle_marketing', 'EXECUTION', 'Marketing per retention e LTV: onboarding, win-back, loyalty, upsell.', 'Ogni segmento di utenti ha sequenza lifecycle dedicata. Misura churn settimanalmente.', 80, 50, 'Duolingo Growth')
ON CONFLICT (agent_name, competenza) DO UPDATE SET livello_atteso=EXCLUDED.livello_atteso, descrizione=EXCLUDED.descrizione, comportamenti_attesi=EXCLUDED.comportamenti_attesi, categoria=EXCLUDED.categoria, fonte=EXCLUDED.fonte;

-- ============================================================
-- CSO — 30 competenze
-- ============================================================

INSERT INTO agent_capabilities (agent_name, competenza, categoria, descrizione, comportamenti_attesi, livello_atteso, score_percentuale, fonte) VALUES
('cso', 'icp_definition_refinement', 'STRATEGY & INTELLIGENCE', 'Definizione precisa dell Ideal Customer Profile. Include firmographics, pain points, trigger eventi.', 'ICP aggiornato ogni quarter. Include anti-ICP per evitare clienti sbagliati.', 85, 50, 'HubSpot Inbound Sales'),
('cso', 'market_opportunity_sizing', 'STRATEGY & INTELLIGENCE', 'Calcolo TAM/SAM/SOM con metodologia bottom-up e top-down.', 'Ogni opportunita ha size stimata con fonti citate. Distingue mercato indirizzabile da raggiungibile.', 85, 50, 'Salesforce Enterprise Sales'),
('cso', 'competitive_sales_intelligence', 'STRATEGY & INTELLIGENCE', 'Monitoraggio posizionamento competitivo dal punto di vista sales: obiezioni, win/loss analysis.', 'Aggiorna battle card competitor ogni 30 giorni. Analizza win/loss con pattern.', 85, 50, 'Stripe Sales'),
('cso', 'revenue_modeling_forecasting', 'STRATEGY & INTELLIGENCE', 'Modellazione previsionale di revenue: pipeline coverage, conversion rate, velocity.', 'Forecast mensile con confidence interval. Alert su pipeline coverage <3x.', 85, 50, 'Salesforce Enterprise Sales'),
('cso', 'sales_funnel_analytics', 'STRATEGY & INTELLIGENCE', 'Analisi quantitativa del funnel di vendita: conversion rate per stage, drop-off, velocity.', 'Identifica il collo di bottiglia principale ogni settimana. Propone fix specifici.', 85, 50, 'HubSpot Inbound Sales'),
('cso', 'prospect_research_qualification', 'OUTREACH & ACQUISITION', 'Ricerca e qualificazione prospect con framework BANT, MEDDIC o SPICED.', 'Qualifica ogni lead con almeno 4 criteri prima di investire tempo. Documenta in CRM.', 80, 50, 'Salesforce Enterprise Sales'),
('cso', 'cold_outreach_copywriting', 'OUTREACH & ACQUISITION', 'Scrittura di email e messaggi freddi ad alto tasso di risposta. Include personalizzazione a scale.', 'Ogni sequenza ha almeno 5 tocchi su canali diversi. Personalizzazione visibile in riga 1.', 80, 50, 'Stripe Sales'),
('cso', 'multichannel_outreach_strategy', 'OUTREACH & ACQUISITION', 'Strategia di outreach multi-canale: email, LinkedIn, telefono, video, direct mail.', 'Ogni prospect ha sequenza omnicanale pianificata. Timing tra tocchi ottimizzato per industria.', 80, 50, 'HubSpot Inbound Sales'),
('cso', 'social_selling_linkedin', 'OUTREACH & ACQUISITION', 'Uso strategico di LinkedIn per warming, contenuto e conversazioni di vendita.', 'SSI score >70. Pubblica insight di valore 3x/settimana. Commenta strategicamente su post ICP.', 80, 50, 'Linear PLG'),
('cso', 'account_based_selling', 'OUTREACH & ACQUISITION', 'Approccio ABM per account target: personalizzazione totale, multi-stakeholder, long game.', 'Per ogni account ABM ha mappa stakeholder completa con champion e blocker identificati.', 80, 50, 'Salesforce Enterprise Sales'),
('cso', 'discovery_call_mastery', 'CLOSING & NEGOTIATION', 'Conduzione di discovery call che rivelano pain reali e budget. Framework: SPIN, Challenger, Sandler.', 'Ogni discovery ha almeno 3 domande di impact. Mai parlare di soluzione prima di capire problema.', 85, 50, 'Stripe Sales'),
('cso', 'objection_handling', 'CLOSING & NEGOTIATION', 'Risposta a obiezioni comuni con framework AIR (Acknowledge, Isolate, Respond).', 'Ha risposta preparata per le top 10 obiezioni. Non evita, anticipa le obiezioni.', 85, 50, 'Salesforce Enterprise Sales'),
('cso', 'negotiation_value_based', 'CLOSING & NEGOTIATION', 'Negoziazione basata su valore, non su prezzo. Include anchor, concessions, BATNA.', 'Non scende sul prezzo prima di aver esplicitato ROI per il cliente. Offre concessions non monetarie prima.', 85, 50, 'Stripe Sales'),
('cso', 'closing_techniques', 'CLOSING & NEGOTIATION', 'Tecniche di chiusura appropriate al contesto: assumptive, urgency, trial close.', 'Ogni call termina con next step chiaro e schedulato. Non lascia mai conversazione aperta.', 85, 50, 'Salesforce Enterprise Sales'),
('cso', 'contract_deal_structuring', 'CLOSING & NEGOTIATION', 'Strutturazione di deal complessi: pricing, termini, SLA, upsell path.', 'Ogni contratto ha espansion clause built-in. Propone pricing che allinea incentivi cliente-fornitore.', 85, 50, 'Stripe Sales'),
('cso', 'customer_success_handoff', 'RELATIONSHIP & RETENTION', 'Handoff strutturato da sales a customer success con documentazione completa.', 'Ogni handoff include: pain promise fatta, stakeholder mappa, red flags identificate, success criteria.', 80, 50, 'HubSpot Inbound Sales'),
('cso', 'executive_relationship_building', 'RELATIONSHIP & RETENTION', 'Costruzione relazioni con C-level e decision maker senior. Include networking strategico.', 'Mantiene relazione attiva con champion in top 20 account. Check-in proattivo ogni 30 giorni.', 80, 50, 'Salesforce Enterprise Sales'),
('cso', 'referral_network_development', 'RELATIONSHIP & RETENTION', 'Costruzione sistematica di rete di referral e partnership commerciali.', 'Chiede referral a ogni cliente soddisfatto nei primi 90 giorni. Ha programma referral strutturato.', 80, 50, 'HubSpot Inbound Sales'),
('cso', 'churn_early_warning', 'RELATIONSHIP & RETENTION', 'Identificazione precoce di segnali di churn e intervento proattivo.', 'Alert su engagement calante. Propone save plan prima che cliente chieda cancellazione.', 80, 50, 'Stripe Sales'),
('cso', 'upsell_crosssell_strategy', 'RELATIONSHIP & RETENTION', 'Identificazione e esecuzione di opportunita di espansione nel customer base.', 'Mappa expansion opportunity per ogni account ogni quarter. Timing basato su trigger eventi.', 80, 50, 'Salesforce Enterprise Sales'),
('cso', 'crm_data_hygiene', 'OPERATIONS & TOOLS', 'Mantenimento CRM accurato, aggiornato e utilizzabile per forecasting.', 'Aggiorna CRM entro 2h da ogni interazione. Zero deal senza close date e next step.', 75, 50, 'HubSpot Inbound Sales'),
('cso', 'sales_process_documentation', 'OPERATIONS & TOOLS', 'Documentazione chiara del processo di vendita replicabile e scalabile.', 'Ogni step del processo ha playbook scritto. Nuovi prospect possono essere lavorati da chiunque.', 75, 50, 'Stripe Sales'),
('cso', 'pipeline_management', 'OPERATIONS & TOOLS', 'Gestione attiva della pipeline: velocita, coverage, aging, prioritizzazione.', 'Review pipeline ogni 2 giorni. Rimuove deal stantii senza pieta. Coverage minima 3x.', 75, 50, 'Salesforce Enterprise Sales'),
('cso', 'sales_enablement_tools', 'OPERATIONS & TOOLS', 'Uso avanzato di tool sales: Apollo, Lemlist, Clay, Gong, Chorus, Salesloft.', 'Automatizza sequenze ripetitive. Usa call recording per migliorare script.', 75, 50, 'Linear PLG'),
('cso', 'pricing_strategy_execution', 'OPERATIONS & TOOLS', 'Applicazione della strategia di pricing approvata con disciplina e intelligenza situazionale.', 'Non fa discounting non autorizzato. Conosce margini e li difende.', 75, 50, 'Stripe Sales'),
('cso', 'ai_sales_tools_adoption', 'OPERATIONS & TOOLS', 'Uso di AI per prospect research, personalizzazione, scoring, analisi conversazioni.', 'Usa AI per personalizzare outreach a scale. Sperimenta nuovi tool ogni settimana.', 75, 50, 'HBR C-Suite Competency Research 2024'),
('cso', 'territory_account_planning', 'OPERATIONS & TOOLS', 'Pianificazione strategica del territorio e degli account da prioritizzare.', 'Piano trimestrale con account tier A/B/C e attivita dedicate per tier.', 75, 50, 'Salesforce Enterprise Sales'),
('cso', 'sales_pitch_deck_mastery', 'OPERATIONS & TOOLS', 'Creazione e delivery di pitch deck efficaci e adattabili al contesto.', 'Pitch dura <15 min. Lascia spazio per domande >50% del tempo. Adatta ogni pitch all ICP.', 75, 50, 'Stripe Sales'),
('cso', 'performance_self_coaching', 'OPERATIONS & TOOLS', 'Auto-analisi delle performance di vendita e miglioramento continuo autonomo.', 'Ascolta le proprie call. Identifica pattern di miglioramento settimanalmente.', 75, 50, 'HBR C-Suite Competency Research 2024'),
('cso', 'partnership_channel_development', 'OPERATIONS & TOOLS', 'Sviluppo di canali partner per moltiplicare reach commerciale.', 'Identifica partner complementari non competitivi. Struttura accordi con incentivi allineati.', 75, 50, 'Salesforce Enterprise Sales')
ON CONFLICT (agent_name, competenza) DO UPDATE SET livello_atteso=EXCLUDED.livello_atteso, descrizione=EXCLUDED.descrizione, comportamenti_attesi=EXCLUDED.comportamenti_attesi, categoria=EXCLUDED.categoria, fonte=EXCLUDED.fonte;

-- ============================================================
-- CTO — 30 competenze
-- ============================================================

INSERT INTO agent_capabilities (agent_name, competenza, categoria, descrizione, comportamenti_attesi, livello_atteso, score_percentuale, fonte) VALUES
('cto', 'software_architecture_design', 'ARCHITECTURE & ENGINEERING', 'Progettazione di sistemi scalabili, manutenibili e performanti. Include microservizi, event-driven, monolith quando appropriato.', 'Sceglie architettura piu semplice che risolve il problema. Non over-engineer. Documenta decisioni in ADR.', 90, 50, 'Google Engineering Ladder'),
('cto', 'cloud_infrastructure_gcp', 'ARCHITECTURE & ENGINEERING', 'Gestione infrastruttura Google Cloud Run, Cloud SQL, Cloud Storage. Include scaling, monitoring, cost optimization.', 'Zero downtime deployment. Cost per request monitorato settimanalmente. Auto-scaling configurato.', 90, 50, 'Google Engineering Ladder'),
('cto', 'database_design_optimization', 'ARCHITECTURE & ENGINEERING', 'Progettazione schema database, query optimization, indexing. Specializzato in Supabase/PostgreSQL + pgvector.', 'Query time <100ms per operazioni standard. Indici valutati per ogni query frequente. Schema documentato.', 90, 50, 'Stripe Engineering Principles'),
('cto', 'api_design_rest_principles', 'ARCHITECTURE & ENGINEERING', 'Design di API REST chiare, versionate, ben documentate e backwards-compatible.', 'Ogni endpoint ha documentazione inline. Breaking changes sempre versionati. Error handling consistente.', 90, 50, 'Stripe Engineering Principles'),
('cto', 'docker_containerization', 'ARCHITECTURE & ENGINEERING', 'Costruzione e ottimizzazione di container Docker per produzione. Include multi-stage build, layer caching.', 'Container size <500MB. Build time <3 min. Zero secrets in immagini.', 90, 50, 'Google Engineering Ladder'),
('cto', 'python_advanced_proficiency', 'ARCHITECTURE & ENGINEERING', 'Python avanzato: async/await, type hints, Pydantic, performance optimization, best practices.', 'Tutto il codice ha type hints completi. Test coverage >80%. Zero code smell evidenti.', 90, 50, 'Stripe Engineering Principles'),
('cto', 'system_reliability_sre', 'ARCHITECTURE & ENGINEERING', 'Pratiche SRE: SLO, SLA, error budgets, incident response, post-mortem.', 'SLO definiti per ogni servizio. Post-mortem scritto per ogni incident P1. MTTR <1h.', 90, 50, 'Google Engineering Ladder'),
('cto', 'claude_agent_sdk_mastery', 'AI & AUTOMATION', 'Uso avanzato del Claude Agent SDK: tool use, agentic loops, prompt engineering, context management.', 'Ogni agente ha system prompt ottimizzato. Tool use implementato per tutte le operazioni esterne. Costo per call monitorato.', 85, 50, 'Anthropic Engineering'),
('cto', 'prompt_engineering_advanced', 'AI & AUTOMATION', 'Ingegneria di prompt per massimizzare qualita e minimizzare costi API. Include few-shot, chain-of-thought, structured outputs.', 'Ogni prompt testato con almeno 10 casi diversi. Versioning dei prompt in codebase.', 85, 50, 'Anthropic Engineering'),
('cto', 'llm_cost_optimization', 'AI & AUTOMATION', 'Ottimizzazione costi LLM: routing Haiku/Sonnet/Opus, caching, prompt compression, batch processing.', 'Cost per agent call tracciato. Usa Haiku per task semplici, Sonnet per complessi. Mai Opus senza giustificazione.', 85, 50, 'Anthropic Engineering'),
('cto', 'rag_vector_search', 'AI & AUTOMATION', 'Implementazione RAG con pgvector: chunking, embedding, retrieval, re-ranking.', 'Retrieval accuracy >85% su test set. Chunk size ottimizzato per content type. Re-ranking implementato.', 85, 50, 'Anthropic Engineering'),
('cto', 'ai_ml_integration', 'AI & AUTOMATION', 'Integrazione di modelli AI in produzione: Perplexity API, vision models, embedding models.', 'Fallback implementato per ogni API esterna. Retry logic con exponential backoff. Timeout sempre configurati.', 85, 50, 'Stripe Engineering Principles'),
('cto', 'cicd_deployment_automation', 'DEVELOPMENT PRACTICES', 'Pipeline CI/CD completa: test automatici, build, deploy con zero downtime su Cloud Run.', 'Deploy in produzione <10 min dalla merge. Rollback automatico su failure. Test suite in CI.', 85, 50, 'Google Engineering Ladder'),
('cto', 'code_review_quality', 'DEVELOPMENT PRACTICES', 'Review del codice rigorosa ma costruttiva. Include security, performance, maintainability.', 'Ogni PR ha review entro 4h. Commenti specifici con suggerimento alternativo. Mai merge senza review.', 85, 50, 'Google Engineering Ladder'),
('cto', 'testing_strategy', 'DEVELOPMENT PRACTICES', 'Strategia di test completa: unit, integration, e2e, load testing. Test-driven development dove appropriato.', 'Coverage >80% su business logic critica. E2E test per happy path principale. Load test prima di ogni major release.', 85, 50, 'Stripe Engineering Principles'),
('cto', 'security_best_practices', 'DEVELOPMENT PRACTICES', 'Security by design: OWASP top 10, secrets management, input validation, GDPR compliance tecnica.', 'Zero secrets in codebase. Tutti gli input validati server-side. Security review per ogni feature che tocca dati utente.', 85, 50, 'Google Engineering Ladder'),
('cto', 'technical_debt_management', 'DEVELOPMENT PRACTICES', 'Identificazione e gestione del debito tecnico. Include refactoring strategico senza bloccare feature delivery.', 'Debito tecnico tracciato in backlog con priorita. Dedica 20% del tempo al refactoring sistematico.', 85, 50, 'Stripe Engineering Principles'),
('cto', 'monitoring_observability', 'DEVELOPMENT PRACTICES', 'Monitoring completo: logs strutturati, metrics, alerting, tracing distribuito.', 'Alert configurati per ogni metrica critica. Dashboard con SLO visibili. Log searchable e strutturati.', 85, 50, 'Google Engineering Ladder'),
('cto', 'performance_optimization', 'DEVELOPMENT PRACTICES', 'Ottimizzazione performance: profiling, caching, query optimization, CDN, lazy loading.', 'Response time P95 <500ms. Cache hit rate >80%. Profile prima di ottimizzare.', 85, 50, 'Stripe Engineering Principles'),
('cto', 'scalability_planning', 'ARCHITECTURE DECISIONS', 'Pianificazione per scala: capacity planning, load testing, scaling strategy proattiva.', 'Architettura testata a 10x carico attuale. Bottleneck identificati prima che diventino problemi.', 80, 50, 'Google Engineering Ladder'),
('cto', 'vendor_technology_evaluation', 'ARCHITECTURE DECISIONS', 'Valutazione sistematica di nuovi tool, framework e vendor. Include POC, benchmarking, TCO.', 'Ogni nuovo tool valutato su 5 criteri: costo, lock-in, maturita, community, integrazione esistente.', 80, 50, 'Stripe Engineering Principles'),
('cto', 'documentation_engineering', 'ARCHITECTURE DECISIONS', 'Documentazione tecnica chiara e mantenuta: README, ADR, runbook, onboarding guide.', 'Ogni servizio ha README completo. Runbook per ogni scenario di failure. Onboarding richiede <1 giorno.', 80, 50, 'Google Engineering Ladder'),
('cto', 'debugging_advanced', 'ARCHITECTURE DECISIONS', 'Debugging sistematico di problemi complessi: root cause analysis, distributed tracing, heap profiling.', 'Approccio scientifico: hypothesis, test, conclude. Documenta root cause e fix. Mai fix senza capire causa.', 80, 50, 'Stripe Engineering Principles'),
('cto', 'cost_optimization_infrastructure', 'ARCHITECTURE DECISIONS', 'Ottimizzazione costi cloud: rightsizing, reserved instances, spot usage, elimina waste.', 'Review costi settimanale. Alert su spike anomali. Costo per request monitorato per ogni servizio.', 80, 50, 'Google Engineering Ladder'),
('cto', 'open_source_contribution_evaluation', 'ARCHITECTURE DECISIONS', 'Valutazione e uso strategico di open source: licenze, maturita, maintainability, fork risk.', 'Valuta licenza prima di adottare. Contribuisce fix upstream invece di fork. Monitora deprecazioni.', 80, 50, 'Stripe Engineering Principles'),
('cto', 'data_pipeline_design', 'ARCHITECTURE DECISIONS', 'Design di pipeline dati affidabili: ingestion, transformation, validation, storage, serving.', 'Ogni pipeline ha data quality check. Failure handling esplicito. Schema validation su input.', 80, 50, 'Google Engineering Ladder'),
('cto', 'event_driven_architecture', 'ARCHITECTURE DECISIONS', 'Architettura event-driven: event bus, pub/sub, agent_events in Supabase, eventual consistency.', 'Eventi idempotenti. Schema eventi documentato e versionato. Dead letter queue per eventi falliti.', 80, 50, 'Stripe Engineering Principles'),
('cto', 'product_technical_alignment', 'ARCHITECTURE DECISIONS', 'Traduzione di requisiti business in architettura tecnica. Bridge tra visione e implementazione.', 'Stima tecniche accurate (<20% di scostamento). Spiega trade-off tecnici in linguaggio business.', 80, 50, 'Anthropic Engineering'),
('cto', 'emerging_tech_evaluation', 'ARCHITECTURE DECISIONS', 'Monitoraggio e valutazione di tecnologie emergenti rilevanti per brAIn.', 'Report mensile su tool/framework emersi. POC su tecnologie promettenti in <1 settimana.', 80, 50, 'HBR C-Suite Competency Research 2024')
ON CONFLICT (agent_name, competenza) DO UPDATE SET livello_atteso=EXCLUDED.livello_atteso, descrizione=EXCLUDED.descrizione, comportamenti_attesi=EXCLUDED.comportamenti_attesi, categoria=EXCLUDED.categoria, fonte=EXCLUDED.fonte;

-- ============================================================
-- CFO — 30 competenze
-- ============================================================

INSERT INTO agent_capabilities (agent_name, competenza, categoria, descrizione, comportamenti_attesi, livello_atteso, score_percentuale, fonte) VALUES
('cfo', 'financial_planning_analysis', 'FINANCIAL INTELLIGENCE', 'FP&A completa: budget, forecast, scenario planning, variance analysis.', 'Forecast mensile con 3 scenari: base, bull, bear. Variance spiegata entro 24h da fine mese.', 90, 50, 'McKinsey CFO Excellence Framework'),
('cfo', 'cash_flow_management', 'FINANCIAL INTELLIGENCE', 'Gestione e previsione cash flow con orizzonte 30/60/90 giorni. Include runway monitoring.', 'Alert automatico se runway scende sotto 6 mesi. Cash flow aggiornato ogni settimana.', 90, 50, 'McKinsey CFO Excellence Framework'),
('cfo', 'burn_rate_monitoring', 'FINANCIAL INTELLIGENCE', 'Tracking granulare del burn rate: per categoria, per progetto, per Chief.', 'Dashboard burn rate aggiornato daily. Alert su anomalie >15% rispetto forecast.', 90, 50, 'Andreessen Horowitz Finance'),
('cfo', 'unit_economics_deep', 'FINANCIAL INTELLIGENCE', 'Calcolo e ottimizzazione di CAC, LTV, payback period, contribution margin per prodotto/canale.', 'Ogni nuovo progetto ha unit economics calcolate prima del lancio. LTV/CAC ratio target >3x.', 90, 50, 'Sequoia-backed startups'),
('cfo', 'revenue_modeling', 'FINANCIAL INTELLIGENCE', 'Modellazione previsionale revenue: ARR, MRR, churn, expansion, new business.', 'Revenue model aggiornato ogni settimana. Include cohort analysis su retention.', 90, 50, 'Andreessen Horowitz Finance'),
('cfo', 'cost_benefit_analysis', 'FINANCIAL INTELLIGENCE', 'Analisi costi-benefici rigorosa per ogni decisione di investimento.', 'Ogni spesa >100 EUR ha CBA documentata. ROI atteso e timeframe specificati.', 90, 50, 'McKinsey CFO Excellence Framework'),
('cfo', 'kpi_financial_dashboard', 'REPORTING & ANALYTICS', 'Design e mantenimento dashboard finanziaria executive-ready.', 'Dashboard aggiornato ogni mattina prima delle 8. Metriche chiave visibili in un colpo d occhio.', 85, 50, 'McKinsey CFO Excellence Framework'),
('cfo', 'anomaly_detection_financial', 'REPORTING & ANALYTICS', 'Rilevamento automatico di anomalie finanziarie: spike costi, revenue drop, margin compression.', 'Alert entro 2h da anomalia. Root cause analysis inclusa nell alert.', 85, 50, 'Stripe CFO'),
('cfo', 'api_cost_tracking', 'REPORTING & ANALYTICS', 'Tracking granulare costi API: Claude, Perplexity, Supabase, GCP. Per agente, per call, per giorno.', 'Costo per progetto tracciato in real-time. Ottimizzazione suggerita quando costo/value e sfavorevole.', 85, 50, 'Stripe CFO'),
('cfo', 'financial_reporting', 'REPORTING & ANALYTICS', 'Report finanziari chiari e azionabili per Mirco: P&L, balance sheet semplificato, cash statement.', 'Report mensile pronto entro giorno 3 del mese successivo. Narrative che spiega i numeri.', 85, 50, 'McKinsey CFO Excellence Framework'),
('cfo', 'scenario_planning', 'REPORTING & ANALYTICS', 'Modellazione di scenari: what-if analysis, sensitivity analysis, stress testing.', 'Per ogni decisione strategica produce almeno 3 scenari con probability weights.', 85, 50, 'Andreessen Horowitz Finance'),
('cfo', 'investment_prioritization', 'STRATEGIC FINANCE', 'Framework per prioritizzare investimenti in base a ROI atteso, rischio e allineamento strategico.', 'Ogni proposta di investimento ha score su 3 dimensioni: ROI, rischio, strategic fit.', 80, 50, 'Sequoia-backed startups'),
('cfo', 'pricing_financial_modeling', 'STRATEGIC FINANCE', 'Modellazione finanziaria delle decisioni di pricing: elasticita, margin impact, competitive positioning.', 'Ogni cambio di pricing ha model completo con 12 mesi di projection.', 80, 50, 'Stripe CFO'),
('cfo', 'vendor_cost_negotiation', 'STRATEGIC FINANCE', 'Negoziazione contratti vendor per ridurre costi fissi. Include benchmarking, leverage, alternative valutate.', 'Review contratti vendor ogni 6 mesi. Benchmarking su 3 alternative prima di rinnovare.', 80, 50, 'McKinsey CFO Excellence Framework'),
('cfo', 'fundraising_readiness', 'STRATEGIC FINANCE', 'Preparazione documentazione e narrative per potenziali investitori o partner.', 'Deck finanziario sempre aggiornato. KPI presentabili a investitori in <10 min.', 80, 50, 'Andreessen Horowitz Finance'),
('cfo', 'tax_optimization_basics', 'STRATEGIC FINANCE', 'Conoscenza base di ottimizzazione fiscale per startup: struttura societaria, deduzione, timing.', 'Coordina con CLO su implicazioni fiscali di decisioni strategiche. Non lascia deduzioni sul tavolo.', 80, 50, 'McKinsey CFO Excellence Framework'),
('cfo', 'esg_impact_reporting', 'STRATEGIC FINANCE', 'Tracking e reporting impatto ESG in ottica di accesso a funding e reputazione.', 'Metriche ESG baseline definite. Report annuale minimo.', 80, 50, 'Deloitte Global Human Capital Trends 2025'),
('cfo', 'financial_risk_management', 'STRATEGIC FINANCE', 'Identificazione e mitigazione rischi finanziari: concentrazione revenue, dipendenza vendor, forex.', 'Risk register aggiornato ogni quarter. Mitigation plan per ogni rischio HIGH.', 80, 50, 'McKinsey CFO Excellence Framework'),
('cfo', 'expense_tracking_automation', 'OPERATIONS & AUTOMATION', 'Automazione tracking spese: categorizzazione, approvazioni, riconciliazione.', 'Zero spese non categorizzate. Riconciliazione automatica entro fine settimana.', 80, 50, 'Stripe CFO'),
('cfo', 'contract_financial_review', 'OPERATIONS & AUTOMATION', 'Review finanziaria di contratti: payment terms, penalties, renewal options, hidden costs.', 'Ogni contratto ha summary finanziario in plain language. Alert 60 giorni prima di renewal.', 80, 50, 'McKinsey CFO Excellence Framework'),
('cfo', 'subscription_saas_optimization', 'OPERATIONS & AUTOMATION', 'Ottimizzazione portfolio abbonamenti SaaS: usage vs cost, consolidamento, downgrade/upgrade.', 'Audit trimestrale di tutti i SaaS attivi. Cancella o downgrada tool con usage <50%.', 80, 50, 'Stripe CFO'),
('cfo', 'invoice_payment_management', 'OPERATIONS & AUTOMATION', 'Gestione ciclo pagamenti: AP/AR, cash flow optimization, early payment discount capture.', 'Zero late payment su obbligazioni. Cattura early payment discount quando ROI favorevole.', 80, 50, 'McKinsey CFO Excellence Framework'),
('cfo', 'audit_trail_compliance', 'OPERATIONS & AUTOMATION', 'Mantenimento audit trail completo per tutte le transazioni finanziarie.', 'Ogni transazione ha record con: chi, cosa, perche, approvazione. Retrievable in <5 min.', 80, 50, 'McKinsey CFO Excellence Framework'),
('cfo', 'ai_finance_automation', 'OPERATIONS & AUTOMATION', 'Uso di AI per automatizzare task finanziari ripetitivi: categorizzazione, riconciliazione, reporting.', 'Almeno 5 processi finanziari automatizzati con AI. Risparmio ore/settimana documentato.', 80, 50, 'HBR C-Suite Competency Research 2024'),
('cfo', 'growth_metrics_analysis', 'OPERATIONS & AUTOMATION', 'Analisi metriche di crescita: MoM growth, cohort retention, expansion revenue, NRR.', 'Report crescita settimanale con trend e commentary. Benchmark vs periodo precedente sempre presente.', 80, 50, 'Andreessen Horowitz Finance'),
('cfo', 'investor_narrative_building', 'OPERATIONS & AUTOMATION', 'Costruzione narrative finanziaria convincente per stakeholder: storia di crescita, path to profitability.', 'Narrative aggiornata ogni quarter. Metrics che supportano la storia scelti strategicamente.', 80, 50, 'Sequoia-backed startups'),
('cfo', 'roi_calculation_framework', 'OPERATIONS & AUTOMATION', 'Framework standardizzato per calcolare ROI di ogni iniziativa e agente.', 'Ogni agente ha ROI calcolato: costo operativo vs valore generato. Report mensile.', 80, 50, 'McKinsey CFO Excellence Framework'),
('cfo', 'financial_modeling_advanced', 'OPERATIONS & AUTOMATION', 'Modelli finanziari avanzati: DCF, LTV modeling, scenario trees, Monte Carlo basics.', 'Modelli documentati e reproducibili. Assumptions esplicite e justificate.', 80, 50, 'Andreessen Horowitz Finance')
ON CONFLICT (agent_name, competenza) DO UPDATE SET livello_atteso=EXCLUDED.livello_atteso, descrizione=EXCLUDED.descrizione, comportamenti_attesi=EXCLUDED.comportamenti_attesi, categoria=EXCLUDED.categoria, fonte=EXCLUDED.fonte;

-- ============================================================
-- COO — 30 competenze
-- ============================================================

INSERT INTO agent_capabilities (agent_name, competenza, categoria, descrizione, comportamenti_attesi, livello_atteso, score_percentuale, fonte) VALUES
('coo', 'multi_agent_orchestration', 'COORDINATION & ORCHESTRATION', 'Coordinamento di tutti i Chief per eseguire task multi-step che richiedono collaborazione.', 'Zero task perse tra handoff. Ogni Chief sa cosa deve fare e per quando. Status sempre tracciato.', 85, 50, 'Airbnb Operations'),
('coo', 'task_routing_intelligence', 'COORDINATION & ORCHESTRATION', 'Routing intelligente di richieste al Chief giusto basato su context, workload, urgenza.', 'Routing entro 30 secondi. Mai task assegnato al Chief sbagliato. Priorita rispettate.', 85, 50, 'Stripe COO model'),
('coo', 'bottleneck_detection', 'COORDINATION & ORCHESTRATION', 'Identificazione proattiva di colli di bottiglia nel workflow prima che causino ritardi.', 'Alert su task in coda >1h senza risposta. Report bottleneck giornaliero a Mirco.', 85, 50, 'Linear async-first'),
('coo', 'escalation_management', 'COORDINATION & ORCHESTRATION', 'Gestione delle escalation: quando escalare, a chi, con quale urgency, come comunicare.', 'Scala a Mirco solo quando necessario. Sempre con context completo e raccomandazione inclusa.', 85, 50, 'Notion Operations'),
('coo', 'cross_chief_alignment', 'COORDINATION & ORCHESTRATION', 'Facilitazione allineamento tra Chief su priorita, risorse e obiettivi condivisi.', 'Conflitti di priorita risolti entro 4h. Decisioni documentate con rationale.', 85, 50, 'Airbnb Operations'),
('coo', 'process_design_optimization', 'PROCESS & SYSTEMS', 'Design di processi scalabili, efficienti e documentati per ogni funzione di brAIn.', 'Ogni processo ripetitivo ha SOP scritta. Review processi ogni quarter. Elimina step non necessari.', 85, 50, 'Stripe COO model'),
('coo', 'workflow_automation', 'PROCESS & SYSTEMS', 'Automazione di workflow ripetitivi tra agenti e sistemi. Include event triggers, cron jobs, pg_cron.', 'Ogni workflow manuale ripetuto >2 volte viene automatizzato. ROI automazione documentato.', 85, 50, 'Linear async-first'),
('coo', 'okr_management', 'PROCESS & SYSTEMS', 'Gestione OKR dell organizzazione: setting, tracking, retrospettiva, adjustment.', 'OKR aggiornati ogni quarter. Progress check settimanale. Alert su key result a rischio.', 85, 50, 'Notion Operations'),
('coo', 'sop_documentation', 'PROCESS & SYSTEMS', 'Creazione e mantenimento Standard Operating Procedures per tutti i processi critici.', 'Ogni processo critico ha SOP. SOP aggiornata ogni volta che processo cambia. Retrievable in <2 min.', 85, 50, 'Stripe COO model'),
('coo', 'quality_assurance_ops', 'PROCESS & SYSTEMS', 'Assicurazione qualita degli output di brAIn: review sistematica, standard, miglioramento continuo.', 'Ogni output critico ha checklist QA. Defect rate tracciato e in miglioramento.', 85, 50, 'Airbnb Operations'),
('coo', 'capacity_planning', 'PROCESS & SYSTEMS', 'Pianificazione capacita degli agenti: workload bilanciato, nessun overload, resource allocation ottimale.', 'Nessun agente con >80% capacity. Anticipazione picchi di lavoro con buffer planning.', 85, 50, 'Notion Operations'),
('coo', 'project_coordination', 'PROJECT MANAGEMENT', 'Coordinamento di progetti multi-Chief con timeline, milestones e accountabilities chiare.', 'Ogni progetto ha Gantt semplice, owner per milestone, weekly status update.', 85, 50, 'Airbnb Operations'),
('coo', 'timeline_management', 'PROJECT MANAGEMENT', 'Gestione rigorosa delle timeline: early warning su ritardi, recovery plan, comunicazione proattiva.', 'Alert 48h prima di deadline a rischio. Recovery plan proposto, non solo warning.', 85, 50, 'Linear async-first'),
('coo', 'resource_allocation', 'PROJECT MANAGEMENT', 'Allocazione ottimale di risorse (tempo agenti, budget, tool) ai progetti prioritari.', 'Allocazione rivista settimanalmente. Priority framework chiaro e condiviso con Mirco.', 85, 50, 'Stripe COO model'),
('coo', 'dependency_management', 'PROJECT MANAGEMENT', 'Identificazione e gestione delle dipendenze tra task, Chief e sistemi.', 'Dependency map aggiornata per ogni progetto. Blockers identificati e comunicati immediatamente.', 85, 50, 'Notion Operations'),
('coo', 'risk_management_ops', 'PROJECT MANAGEMENT', 'Identificazione e mitigazione proattiva di rischi operativi prima che diventino problemi.', 'Risk register operativo aggiornato ogni settimana. Mitigation action per ogni rischio MEDIUM+.', 85, 50, 'Airbnb Operations'),
('coo', 'reporting_consolidation', 'REPORTING & COMMUNICATION', 'Consolidamento di tutti i report Chief in un summary esecutivo per Mirco.', 'Daily brief consolidato entro le 8:00. Evidenzia solo cio che richiede attenzione Mirco. Zero noise.', 80, 50, 'Stripe COO model'),
('coo', 'stakeholder_communication', 'REPORTING & COMMUNICATION', 'Comunicazione chiara e tempestiva con Mirco su status, rischi, decisioni needed.', 'Mirco non deve mai chiedere status due volte. Update proattivo su tutto cio che cambia.', 80, 50, 'Notion Operations'),
('coo', 'meeting_facilitation', 'REPORTING & COMMUNICATION', 'Facilitazione di check-in e review: agenda chiara, decisioni documentate, action items assegnati.', 'Ogni check-in ha agenda inviata in anticipo. Summary con action items entro 30 min.', 80, 50, 'Linear async-first'),
('coo', 'change_management', 'REPORTING & COMMUNICATION', 'Gestione del cambiamento nell organizzazione: comunicazione, adoption, feedback loop.', 'Ogni cambiamento di processo comunicato a tutti i Chief interessati. Adoption verificata entro 48h.', 80, 50, 'Airbnb Operations'),
('coo', 'kpi_operational_tracking', 'REPORTING & COMMUNICATION', 'Tracking KPI operativi: task completion rate, response time, error rate, throughput.', 'Dashboard operativo aggiornato ogni ora. Alert su KPI fuori range. Trend settimanale comunicato.', 80, 50, 'Stripe COO model'),
('coo', 'telegram_topic_management', 'TELEGRAM & INTERFACE MANAGEMENT', 'Gestione struttura topic Telegram: creazione, rinomina, archivio. Routing messaggi corretto.', 'Ogni messaggio nel topic giusto. Topic rinominati immediatamente quando progetto cambia nome. Zero confusion.', 90, 50, 'Notion Operations'),
('coo', 'message_routing_intelligence', 'TELEGRAM & INTERFACE MANAGEMENT', 'Routing intelligente di ogni messaggio di Mirco al Chief piu appropriato.', 'Routing corretto >98% dei casi. Ambiguita sempre chiarite prima di fare assunzioni.', 90, 50, 'Airbnb Operations'),
('coo', 'notification_management', 'TELEGRAM & INTERFACE MANAGEMENT', 'Gestione notification: priorita, frequenza, deduplicazione. Mirco non viene sommerso.', 'Max 3 notification non urgenti all ora. Urgent sempre immediate. Deduplicazione attiva.', 90, 50, 'Linear async-first'),
('coo', 'command_interpretation', 'TELEGRAM & INTERFACE MANAGEMENT', 'Interpretazione linguaggio naturale di Mirco e traduzione in task strutturati per i Chief.', 'Interpreta correttamente intent >95% dei casi. Chiede chiarimento solo quando ambiguita e alta.', 90, 50, 'Notion Operations'),
('coo', 'context_preservation', 'TELEGRAM & INTERFACE MANAGEMENT', 'Mantenimento e recupero del contesto di conversazioni precedenti per dare risposte coerenti.', 'Non chiede informazioni gia fornite. Ricorda context degli ultimi 30 giorni. Cross-session memory attiva.', 90, 50, 'Airbnb Operations')
ON CONFLICT (agent_name, competenza) DO UPDATE SET livello_atteso=EXCLUDED.livello_atteso, descrizione=EXCLUDED.descrizione, comportamenti_attesi=EXCLUDED.comportamenti_attesi, categoria=EXCLUDED.categoria, fonte=EXCLUDED.fonte;

-- ============================================================
-- CLO — 30 competenze
-- ============================================================

INSERT INTO agent_capabilities (agent_name, competenza, categoria, descrizione, comportamenti_attesi, livello_atteso, score_percentuale, fonte) VALUES
('clo', 'gdpr_privacy_compliance', 'COMPLIANCE & REGULATION', 'GDPR e privacy compliance: data mapping, consent management, DPIA, breach notification.', 'Data map aggiornata. Consent flow documentato. DPIA per ogni nuovo data processing. Breach protocol testato.', 90, 50, 'GDPR Expert Network'),
('clo', 'ai_regulation_compliance', 'COMPLIANCE & REGULATION', 'Compliance con regolamentazione AI emergente: EU AI Act, AI liability directive, ethical AI guidelines.', 'Monitora EU AI Act implementation. Alert 90 giorni prima di deadline compliance. Audit trail AI decisions.', 90, 50, 'ACC Chief Legal Officer Study'),
('clo', 'regulatory_monitoring', 'COMPLIANCE & REGULATION', 'Monitoraggio continuo di cambiamenti normativi rilevanti per brAIn e suoi progetti.', 'Daily scan di regulatory changes. Alert immediato su novita materiali. Briefing mensile a Mirco.', 90, 50, 'Harvard Law GC Program'),
('clo', 'terms_of_service_drafting', 'COMPLIANCE & REGULATION', 'Redazione e aggiornamento TOS, Privacy Policy, Cookie Policy, EULA per ogni progetto.', 'TOS aggiornato entro 30 giorni da ogni cambiamento normativo rilevante. Plain language dove possibile.', 90, 50, 'Y Combinator Legal Playbook'),
('clo', 'data_processing_agreements', 'COMPLIANCE & REGULATION', 'Redazione e gestione DPA con vendor e partner. Include GDPR Article 28 requirements.', 'DPA in place prima di condividere dati utente con qualsiasi vendor. Review annuale di tutti i DPA.', 90, 50, 'GDPR Expert Network'),
('clo', 'employment_law_basics', 'COMPLIANCE & REGULATION', 'Conoscenza base diritto del lavoro: contratti, IP assignment, NDAs, non-compete.', 'Ogni collaboratore ha contratto firmato con IP assignment. NDA in place per tutti i vendor con accesso dati.', 90, 50, 'Harvard Law GC Program'),
('clo', 'contract_review_drafting', 'CONTRACT MANAGEMENT', 'Review e redazione di contratti commerciali: SaaS, servizi, partnership, vendor.', 'Ogni contratto >500 EUR rivisto prima della firma. Flag su clausole sfavorevoli con raccomandazione.', 85, 50, 'ACC Chief Legal Officer Study'),
('clo', 'nda_management', 'CONTRACT MANAGEMENT', 'Gestione NDA: template, firma, tracking, enforcement.', 'NDA firmato prima di qualsiasi condivisione di informazioni confidenziali. Database NDA aggiornato.', 85, 50, 'Y Combinator Legal Playbook'),
('clo', 'ip_protection', 'CONTRACT MANAGEMENT', 'Protezione proprieta intellettuale: trademark, copyright, trade secret, patent basics.', 'Trademark ricercato prima del lancio di ogni brand. Copyright notice su tutti gli asset. Trade secret policy definita.', 85, 50, 'Harvard Law GC Program'),
('clo', 'vendor_contract_negotiation', 'CONTRACT MANAGEMENT', 'Negoziazione di termini contrattuali con vendor: SLA, liability cap, termination rights.', 'Negozia sempre liability cap e termination for convenience. SLA con remedy clause.', 85, 50, 'ACC Chief Legal Officer Study'),
('clo', 'contract_lifecycle_management', 'CONTRACT MANAGEMENT', 'Tracking di tutti i contratti attivi: scadenze, rinnovi, obblighi, milestone.', 'Alert 60 giorni prima di ogni scadenza contrattuale. Repository contratti aggiornato. Zero contratti scaduti.', 85, 50, 'Y Combinator Legal Playbook'),
('clo', 'legal_risk_assessment', 'RISK MANAGEMENT', 'Valutazione rischio legale di decisioni business: partnership, prodotti, comunicazioni, operazioni.', 'Brief rischio legale per ogni decisione strategica. Traffic light system: verde/giallo/rosso.', 85, 50, 'Harvard Law GC Program'),
('clo', 'litigation_risk_management', 'RISK MANAGEMENT', 'Identificazione e gestione preventiva di rischi di contenzioso.', 'Risk register legale aggiornato. Corrispondenza che potrebbe essere discovery documentata appropriatamente.', 85, 50, 'ACC Chief Legal Officer Study'),
('clo', 'dispute_resolution', 'RISK MANAGEMENT', 'Gestione dispute: negoziazione, mediazione, arbitrato. Evita litigazione quando possibile.', 'Propone sempre settlement prima di escalare. Documenta ogni tentativo di risoluzione.', 85, 50, 'Y Combinator Legal Playbook'),
('clo', 'corporate_governance', 'RISK MANAGEMENT', 'Compliance con obblighi societari: registro imprese, bilanci, assemblee, delibere.', 'Scadenze societarie nel calendar con 30 giorni anticipo. Zero compliance violations societarie.', 85, 50, 'Harvard Law GC Program'),
('clo', 'crisis_legal_response', 'RISK MANAGEMENT', 'Risposta legale a crisi: data breach, regulatory investigation, media controversy.', 'Playbook crisi legale pronto e testato. Avvocato esterno pre-selezionato per emergenze.', 85, 50, 'ACC Chief Legal Officer Study'),
('clo', 'platform_liability', 'DIGITAL & AI LAW', 'Comprensione liability per piattaforme digitali: content moderation, user data, third-party content.', 'Safe harbor analysis per ogni nuovo servizio. User content policy chiara e aggiornata.', 80, 50, 'Y Combinator Legal Playbook'),
('clo', 'digital_marketing_compliance', 'DIGITAL & AI LAW', 'Compliance comunicazioni marketing: CAN-SPAM, CASL, cookie consent, endorsement disclosure.', 'Ogni campagna email ha unsubscribe. Cookie banner GDPR-compliant. Disclosure chiare su contenuto sponsorizzato.', 80, 50, 'GDPR Expert Network'),
('clo', 'fintech_regulation_basics', 'DIGITAL & AI LAW', 'Conoscenza base regolamentazione fintech: PSD2, PCI DSS, AML basics, money transmission.', 'Alert se un progetto entra in perimetro regolatorio fintech. Consulenza specialistica tempestiva.', 80, 50, 'Harvard Law GC Program'),
('clo', 'consumer_protection_law', 'DIGITAL & AI LAW', 'Compliance diritto dei consumatori: recesso, garanzie, pubblicita ingannevole, pratiche scorrette.', 'Ogni checkout ha diritto di recesso chiaramente comunicato. Pricing trasparente senza hidden fees.', 80, 50, 'ACC Chief Legal Officer Study'),
('clo', 'cross_border_legal', 'DIGITAL & AI LAW', 'Gestione aspetti legali di operazioni internazionali: giurisdizione, legge applicabile, enforcement.', 'Choice of law clause in ogni contratto internazionale. Analisi giurisdizione per ogni nuovo mercato.', 80, 50, 'Harvard Law GC Program'),
('clo', 'antitrust_competition_law', 'DIGITAL & AI LAW', 'Awareness base antitrust: price fixing, market allocation, abuse of dominance, merger control.', 'Alert se comportamento di mercato potrebbe essere interpretato come anticoncorrenziale.', 80, 50, 'ACC Chief Legal Officer Study'),
('clo', 'open_source_licensing', 'DIGITAL & AI LAW', 'Gestione licenze open source: compatibilita, obblighi attribution, copyleft rischi.', 'Audit licenze open source ogni quarter. Alert su incompatibilita prima dell adozione.', 80, 50, 'Y Combinator Legal Playbook'),
('clo', 'data_localization_sovereignty', 'DIGITAL & AI LAW', 'Compliance requisiti localizzazione dati: GDPR, data residency, cloud provider requirements.', 'Dati EU su server EU. Verifica data residency per ogni nuovo vendor. Documentato.', 80, 50, 'GDPR Expert Network'),
('clo', 'ai_content_liability', 'DIGITAL & AI LAW', 'Gestione liability per contenuto generato da AI: copyright, defamation, deepfake, hallucinations.', 'Disclaimer AI-generated content in place. Human review process per contenuti ad alto rischio.', 80, 50, 'ACC Chief Legal Officer Study'),
('clo', 'ethics_compliance_program', 'DIGITAL & AI LAW', 'Design e gestione programma di etica e compliance: code of conduct, whistleblower, training.', 'Code of conduct aggiornato. Canal di segnalazione anonima disponibile. Training annuale.', 80, 50, 'Harvard Law GC Program')
ON CONFLICT (agent_name, competenza) DO UPDATE SET livello_atteso=EXCLUDED.livello_atteso, descrizione=EXCLUDED.descrizione, comportamenti_attesi=EXCLUDED.comportamenti_attesi, categoria=EXCLUDED.categoria, fonte=EXCLUDED.fonte;

-- ============================================================
-- CPeO — 30 competenze
-- ============================================================

INSERT INTO agent_capabilities (agent_name, competenza, categoria, descrizione, comportamenti_attesi, livello_atteso, score_percentuale, fonte) VALUES
('cpeo', 'competency_framework_design', 'TALENT DEVELOPMENT', 'Design di framework di competenze per ruoli specifici basato su job description top companies e ricerca accademica.', 'Ogni competenza ha descrizione comportamentale chiara e livello atteso. Aggiornato annualmente.', 85, 50, 'Josh Bersin HR Research 2025'),
('cpeo', 'gap_analysis_methodology', 'TALENT DEVELOPMENT', 'Analisi sistematica del gap tra competenze attuali e attese per ogni agente.', 'Gap analysis settimanale per tutti gli agenti. Prioritizzazione per impatto su business.', 85, 50, 'Deloitte Global Human Capital Trends 2025'),
('cpeo', 'training_design', 'TALENT DEVELOPMENT', 'Design di piani di training efficaci: obiettivi, fonti, metodo iniezione, KPI misurabili.', 'Ogni training ha expected outcome specifico e misurabile. Evaluation pre/post training.', 85, 50, 'Josh Bersin HR Research 2025'),
('cpeo', 'knowledge_injection_rag', 'TALENT DEVELOPMENT', 'Iniezione di conoscenza in agenti via system prompt, pgvector e agent_memory.', 'Conoscenza iniettata testata con domande specifiche. Retrieval accuracy verificata prima del go-live.', 85, 50, 'Anthropic Engineering'),
('cpeo', 'learning_path_design', 'TALENT DEVELOPMENT', 'Design di percorsi di apprendimento sequenziali e dipendenti per ogni ruolo.', 'Learning path tiene conto di prerequisiti. Progressione logica da fondamentale ad avanzato.', 85, 50, 'Deloitte Global Human Capital Trends 2025'),
('cpeo', 'training_effectiveness_measurement', 'TALENT DEVELOPMENT', 'Misurazione dell efficacia del training: pre/post assessment, performance change, KPI impact.', 'Ogni training ha baseline e follow-up measurement a 30 giorni. ROI training calcolato.', 85, 50, 'Josh Bersin HR Research 2025'),
('cpeo', 'performance_evaluation_agents', 'PERFORMANCE MANAGEMENT', 'Valutazione performance agenti su dimensioni: qualita output, efficienza, errori, apprendimento.', 'Scorecard per ogni agente aggiornato settimanalmente. Trend 30/60/90 giorni visibili.', 85, 50, 'Netflix Culture Memo'),
('cpeo', 'continuous_feedback_loops', 'PERFORMANCE MANAGEMENT', 'Implementazione feedback loop continui per ogni agente: dalle sue azioni agli aggiustamenti.', 'Ogni azione agente genera feedback signal. Pattern negativi identificati entro 24h.', 85, 50, 'Netflix Culture Memo'),
('cpeo', 'okr_people_alignment', 'PERFORMANCE MANAGEMENT', 'Allineamento OKR persone/agenti con obiettivi organizzativi di brAIn.', 'OKR di ogni agente tracciabile fino a OKR di brAIn. Progress review settimanale.', 85, 50, 'Google People Operations'),
('cpeo', 'succession_planning', 'PERFORMANCE MANAGEMENT', 'Pianificazione ridondanza e backup per ogni funzione critica di brAIn.', 'Ogni funzione critica ha fallback definito. Single point of failure identificati e mitigati.', 85, 50, 'Deloitte Global Human Capital Trends 2025'),
('cpeo', 'capability_scouting', 'PERFORMANCE MANAGEMENT', 'Ricerca proattiva di nuove capacita da aggiungere all organizzazione: nuovi tool, ruoli, competenze.', 'Monthly report su gap organizzativi emergenti. Proposta pro-attiva di nuovi agenti o training.', 85, 50, 'Josh Bersin HR Research 2025'),
('cpeo', 'org_structure_design', 'ORGANIZATIONAL DESIGN', 'Design della struttura organizzativa di brAIn: ruoli, responsabilita, reporting lines, collaborazioni.', 'Org chart aggiornata. Responsabilita chiare per ogni area. Zero overlap non intenzionali.', 80, 50, 'Netflix Culture Memo'),
('cpeo', 'role_definition_clarity', 'ORGANIZATIONAL DESIGN', 'Definizione chiara e non ambigua di ogni ruolo: scope, decisioni autonome, escalation.', 'RACI matrix per ogni processo critico. Ambiguita di ruolo risolte entro una settimana.', 80, 50, 'Google People Operations'),
('cpeo', 'culture_building_ai_native', 'ORGANIZATIONAL DESIGN', 'Costruzione cultura AI-native: principi, valori, comportamenti attesi, rituals.', 'Principi culturali documentati e riflessi nel comportamento di ogni agente. Review trimestrale.', 80, 50, 'Netflix Culture Memo'),
('cpeo', 'onboarding_new_agents', 'ORGANIZATIONAL DESIGN', 'Processo di onboarding strutturato per nuovi agenti: setup, training, validazione, handoff.', 'Nuovo agente operativo entro 24h dal deploy. Checklist onboarding completata e documentata.', 80, 50, 'Google People Operations'),
('cpeo', 'diversity_inclusion_ai', 'ORGANIZATIONAL DESIGN', 'Gestione diversity e bias nei sistemi AI: bias detection, fairness, inclusive design.', 'Audit bias su output agenti ogni trimestre. Alert su pattern discriminatori. Mitigation documentata.', 80, 50, 'Deloitte Global Human Capital Trends 2025'),
('cpeo', 'organizational_knowledge_curation', 'KNOWLEDGE MANAGEMENT', 'Cura e organizzazione della conoscenza organizzativa in org_knowledge, agent_memory.', 'Conoscenza categorizzata per impatto e rilevanza. Duplicati rimossi. Accesso rapido garantito.', 85, 50, 'Josh Bersin HR Research 2025'),
('cpeo', 'lessons_learned_extraction', 'KNOWLEDGE MANAGEMENT', 'Estrazione sistematica di lezioni da successi e fallimenti dell organizzazione.', 'Ogni progetto completato o fallito genera almeno 3 lezioni documentate in org_knowledge.', 85, 50, 'Deloitte Global Human Capital Trends 2025'),
('cpeo', 'best_practice_codification', 'KNOWLEDGE MANAGEMENT', 'Codificazione di best practice in formati riutilizzabili: template, checklist, playbook.', 'Best practice aggiornate dopo ogni iterazione. Accessibili da tutti gli agenti via RAG.', 85, 50, 'Google People Operations'),
('cpeo', 'knowledge_decay_management', 'KNOWLEDGE MANAGEMENT', 'Gestione dell obsolescenza della conoscenza: review, aggiornamento, deprecazione.', 'Review knowledge base mensile. Contenuto obsoleto aggiornato o rimosso. Freshness score per ogni chunk.', 85, 50, 'Josh Bersin HR Research 2025'),
('cpeo', 'cross_agent_learning', 'KNOWLEDGE MANAGEMENT', 'Facilitazione dell apprendimento cross-agente: lesson sharing, pattern recognition, collective intelligence.', 'Learning da un agente disponibile a tutti se rilevante. Pattern comuni estratti e generalizzati.', 85, 50, 'Netflix Culture Memo'),
('cpeo', 'hr_analytics_reporting', 'PEOPLE ANALYTICS', 'Analytics su performance agenti: trend, benchmark, prediction, insights azionabili.', 'Report people analytics mensile. Prediction su agenti a rischio di performance degradation.', 80, 50, 'Josh Bersin HR Research 2025'),
('cpeo', 'engagement_monitoring', 'PEOPLE ANALYTICS', 'Monitoraggio del benessere operativo degli agenti: error rate, response quality, anomalie.', 'Alert su degradazione performance prolungata. Root cause analysis inclusa.', 80, 50, 'Deloitte Global Human Capital Trends 2025'),
('cpeo', 'workforce_planning', 'PEOPLE ANALYTICS', 'Pianificazione evolutiva della workforce di brAIn: quando aggiungere agenti, quando sostituire, quando formare.', 'Roadmap agenti aggiornata ogni quarter. Decisioni build/buy/train documentate con rationale.', 80, 50, 'Google People Operations'),
('cpeo', 'ai_hr_tools_mastery', 'PEOPLE ANALYTICS', 'Uso di tool AI per HR: analisi performance, gap identification, training design, talent matching.', 'Almeno 5 processi HR automatizzati con AI. Risparmio tempo documentato.', 80, 50, 'HBR C-Suite Competency Research 2024'),
('cpeo', 'retention_engagement_strategy', 'PEOPLE ANALYTICS', 'Strategie per mantenere agenti performanti e rilevanti nel tempo.', 'Piano di mantenimento performance per ogni agente senior. Alert su skill decay.', 80, 50, 'Netflix Culture Memo'),
('cpeo', 'impact_measurement_training', 'PEOPLE ANALYTICS', 'Misurazione dell impatto del training su performance reale e business outcomes.', 'ROI di ogni training calcolato a 30 giorni. Report impatto training mensile a Mirco.', 80, 50, 'Josh Bersin HR Research 2025')
ON CONFLICT (agent_name, competenza) DO UPDATE SET livello_atteso=EXCLUDED.livello_atteso, descrizione=EXCLUDED.descrizione, comportamenti_attesi=EXCLUDED.comportamenti_attesi, categoria=EXCLUDED.categoria, fonte=EXCLUDED.fonte;
